# Generated by Django 5.1.4 on 2024-12-12 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudantes',
            new_name='Estudante',
        ),
    ]
